### ISSUE TITLE
impostersController - Api is broken with NodeJS v6.2

### ISSUE THREAD

**Issue by RookY2K** [bbyars/mountebank#144]
#### Expected behaviour
Should be able to delete imposters using delete api method
...

#### Actual behaviour
Exception is thrown: 
Invoke-WebRequest : TypeError: query.hasOwnProperty is not a function
   at queryIsFalse (C:\Utility\Mountebank\node_modules\mountebank\src\controllers\impostersController.js:24:20)
   at del (C:\Utility\Mountebank\node_modules\mountebank\src\controllers\impostersController.js:165:29)
   at Layer.handle [as handle_request] (C:\Utility\Mountebank\node_modules\mountebank\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Utility\Mountebank\node_modules\mountebank\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Utility\Mountebank\node_modules\mountebank\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Utility\Mountebank\node_modules\mountebank\node_modules\express\lib\router\layer.js:95:5)
   at C:\Utility\Mountebank\node_modules\mountebank\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\Utility\Mountebank\node_modules\mountebank\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Utility\Mountebank\node_modules\mountebank\node_modules\express\lib\router\index.js:271:10)
   at cors (C:\Utility\Mountebank\node_modules\mountebank\node_modules\cors\lib\index.js:178:7)
...

#### Steps to reproduce
1) Ensure NodeJS version = 6.2
2) Attempt to delete imposters with rest api against http://[mountebankurl]:[port]/imposters 
...

#### Software versions used

```
OS         : Win 7
mountebank : 1.5.1-beta.1115 
node.js    : 6.2
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
{"level":"debug","message":"[mb:2525] config: {\"options\":{\"allowInjection\":false,\"mock\":false,\"debug\":false,\"heroku\":false,\"version\":false,\"help\":false,\"loglevel\":\"debug\",\"port\":2525,\"pidfile\":\"mb.pid\",\"logfile\":\"mb.log\"},\"process\":{\"nodeVersion\":\"v6.2.0\",\"architecture\":\"x64\",\"platform\":\"win32\"}}","timestamp":"2016-05-20T15:24:49.575Z"}
{"level":"info","message":"[mb:2525] DELETE /imposters","timestamp":"2016-05-20T15:25:13.933Z"}

```

The issue is that NodeJS recently updated querystring.js and url.js to initialize the querystring objects with Object.create(null) instead of {}. This means the query object in impostersController.js will not have the hasOwnProperty method. I'm not familiar enough with mountebank's internals to be comfortable enough to replace the hasOwnProperty check with !query[key], but that should fix the issue.

**Comment by RookY2K** [comment]
After more research into nodejs url and querystring modules, I feel comfortable that dropping the hasOwnProperty check is safe. The only properties on the query object will be the query string properties from the request.

**Comment by iamkoch** [comment]
Is this in any released version within npm? It'll block anyone as soon as they upgrade to v6.2 or above.
