### ISSUE TITLE
TypeError: Parameter \"url\" must be a string, not object

### ISSUE THREAD

**Issue by jrnelson333** [bbyars/mountebank#323]
#### Expected behaviour
I expect that I can install mountebank through npm, setup a proxy through a config file, and hit https://google.com through the proxy at https://localhost:8001

...

#### Actual behaviour
I receive an error, `"message": "Parameter \"url\" must be a string, not object",`
...

#### Steps to reproduce
1. on node v5.12 or v8.5 -> npm i mountebank -g
2. Set up config file, `proxy.json`
```
{
    "imposters": [
        {
            "port": 8001,
            "protocol": "https",
            "name": "test",
            "stubs": [
                {
                    "responses": [
                        {
                            "proxy": {
                                "to": {
                                    "host": "google.com",
                                    "port": 80
                                },
                                "mode": "proxyAlways"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```
3. `mb --configfile proxy.json`
4. Attempt to navigate to `https://localhost:8001`
...

#### Software versions used

```
OS         : Mac OS Sierra 10.12.6
mountebank : 1.13.0
node.js    : 5.12, and 8.5.0
  (only if installed via npm)
Installation method : npm
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
{"level":"info","message":"[mb:2525] mountebank v1.13.0 now taking orders - point your browser to http://localhost:2525 for help","timestamp":"2018-01-22T20:01:27.789Z"}
{"level":"debug","message":"[mb:2525] config: {\"options\":{\"help\":false,\"configfile\":\"proxy.json\",\"loglevel\":\"debug\",\"port\":2525,\"noParse\":false,\"pidfile\":\"mb.pid\",\"nologfile\":false,\"logfile\":\"mb.log\",\"allowInjection\":false,\"localOnly\":false,\"ipWhitelist\":[\"*\"],\"mock\":false,\"debug\":false,\"heroku\":false},\"process\":{\"nodeVersion\":\"v8.5.0\",\"architecture\":\"x64\",\"platform\":\"darwin\"}}","timestamp":"2018-01-22T20:01:27.790Z"}
{"level":"info","message":"[mb:2525] PUT /imposters","timestamp":"2018-01-22T20:01:27.812Z"}
{"level":"debug","message":"[mb:2525] ::ffff:127.0.0.1:58471 => {\"imposters\":[{\"port\":8001,\"protocol\":\"https\",\"name\":\"test\",\"stubs\":[{\"responses\":[{\"proxy\":{\"to\":{\"host\":\"google.com\",\"port\":80},\"mode\":\"proxyAlways\"}}]}]}]}","timestamp":"2018-01-22T20:01:27.825Z"}
{"level":"info","message":"[https:8001 test] Open for business...","timestamp":"2018-01-22T20:01:27.855Z"}
{"level":"debug","message":"[https:8001 test] ::ffff:127.0.0.1:58500 ESTABLISHED","timestamp":"2018-01-22T20:01:35.026Z"}
{"level":"info","message":"[https:8001 test] ::ffff:127.0.0.1:58500 => GET /","timestamp":"2018-01-22T20:01:35.032Z"}
{"level":"debug","message":"[https:8001 test] ::ffff:127.0.0.1:58500 => {\"requestFrom\":\"::ffff:127.0.0.1:58500\",\"method\":\"GET\",\"path\":\"/\",\"query\":{},\"headers\":{\"cache-control\":\"no-cache\",\"Postman-Token\":\"cec9bcdd-2f2f-4ac1-8bee-cb94c9936c49\",\"User-Agent\":\"PostmanRuntime/6.4.1\",\"Accept\":\"*/*\",\"Host\":\"localhost:8001\",\"accept-encoding\":\"gzip, deflate\",\"Connection\":\"keep-alive\"},\"body\":\"\"}","timestamp":"2018-01-22T20:01:35.037Z"}
{"level":"debug","message":"[https:8001 test] ::ffff:127.0.0.1:58500 using predicate match: {}","timestamp":"2018-01-22T20:01:35.038Z"}
{"level":"debug","message":"[https:8001 test] ::ffff:127.0.0.1:58500 generating response from {\"proxy\":{\"to\":{\"host\":\"google.com\",\"port\":80},\"mode\":\"proxyAlways\"}}","timestamp":"2018-01-22T20:01:35.038Z"}
{"level":"error","message":"[https:8001 test] ::ffff:127.0.0.1:58500 X=> {\"message\":\"Parameter \\\"url\\\" must be a string, not object\",\"name\":\"TypeError\",\"stack\":\"TypeError: Parameter \\\"url\\\" must be a string, not object\\n    at Url.parse (url.js:102:11)\\n    at Object.urlParse [as parse] (url.js:96:5)\\n    at getProxyRequest (/Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/http/httpProxy.js:50:25)\\n    at Object.to (/Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/http/httpProxy.js:151:30)\\n    at proxyAndRecord (/Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/responseResolver.js:216:22)\\n    at processResponse (/Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/responseResolver.js:235:20)\\n    at Object.resolve (/Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/responseResolver.js:272:16)\\n    at Object.resolve (/Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/stubRepository.js:136:25)\\n    at F.respond (/Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/http/baseHttpServer.js:94:34)\\n    at /Users/qiy895/.nvm/versions/node/v8.5.0/lib/node_modules/mountebank/src/models/abstractServer.js:96:35\"}","timestamp":"2018-01-22T20:01:35.040Z"}
{"level":"debug","message":"[https:8001 test] ::ffff:127.0.0.1:58500 CLOSED","timestamp":"2018-01-22T20:01:40.047Z"}
{"level":"info","message":"[mb:2525] Adios - see you soon?","timestamp":"2018-01-22T20:02:01.134Z"}
```

```
Log contents here
```

**Comment by jrnelson333** [comment]
I was able to resolve this by changing the proxy settings to the following:
```
"proxy": {
  "to": "google.com"
}
                             
```
