### ISSUE TITLE
imposter POST functional tests behave erratically

### ISSUE THREAD

**Issue by moodmosaic** [bbyars/mountebank#40]
On Windows, the grunt task
```
test:functional
```

results in 1 failing test
```
1) tcp imposter POST /imposters with injections should allow asynchronous injection:
   AssertionError: -1 === 0
    at \mountebank\functionalTest\api\tcp\tcpInjectionTest.js:139:24
    at _fulfilled (\mountebank\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (\mountebank\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (\mountebank\node_modules\q\q.js:749:13)
    at \mountebank\node_modules\q\q.js:557:44
    at flush (\mountebank\node_modules\q\q.js:108:17)
    at process._tickDomainCallback (node.js:463:13)
```

and sometimes it results in 2 failing tests
```
1) http imposter POST /imposters with stubs should add latency when using behaviors.wait:
   AssertionError: false == true
    at \mountebank\functionalTest\api\http\httpStubTest.js:194:28
    at _fulfilled (\mountebank\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (\mountebank\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (\mountebank\node_modules\q\q.js:749:13)
    at \mountebank\node_modules\q\q.js:557:44
    at flush (\mountebank\node_modules\q\q.js:108:17)
    at process._tickDomainCallback (node.js:463:13)

2) tcp imposter POST /imposters with injections should allow asynchronous injection:
   AssertionError: -1 === 0
    at \mountebank\functionalTest\api\tcp\tcpInjectionTest.js:139:24
    at _fulfilled (\mountebank\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (\mountebank\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (\mountebank\node_modules\q\q.js:749:13)
    at \mountebank\node_modules\q\q.js:557:44
    at flush (\mountebank\node_modules\q\q.js:108:17)
    at process._tickDomainCallback (node.js:463:13)
```

**Comment by bbyars** [comment]
Ran 10 times in a row on Windows with no failures; assuming the non-determinism has been cleaned up.  Will open a new issue if further non-determinism detected.
