### ISSUE TITLE
"npm install" error with ejs@2.7.4

### ISSUE THREAD

**Issue by pakornsak** [bbyars/mountebank#496]
#119 ## Expected behaviour
Should successfully install "npm install moutebank -g"
...

#### Actual behaviour
Cannot find module '/usr/lib/node_modules/mountebank/node_modules/ejs/postinstall.js' 
...

#### Steps to reproduce
1. run "npm install moutebank -g"
...

#### Software versions used

```
OS         :centOS
mountebank :version (2.1.2)
node.js    : v12.11.1
Installation method :npm
```

#### Log contents in mb.log when running mb --loglevel debug
```
/usr/bin/mb -> /usr/lib/node_modules/mountebank/bin/mb

> ejs@2.7.4 postinstall /usr/lib/node_modules/mountebank/node_modules/ejs
> node ./postinstall.js

internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/mountebank/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@2.7.4 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ejs@2.7.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bbyars** [comment]
Tested on centos 7 with the latest version, that upgraded to the ejs version referenced above. Closing assuming it's fixed; let me know if you still have issues.
