### ISSUE TITLE
CONTAINS operator fails on dicts with int values

### ISSUE THREAD

**Issue by s1r3m** [bbyars/mountebank#607]
#### Expected behavior

MB matches my request and returns the set response.

#### Actual behavior

500 response with a trace of JS error. See the log below

#### Steps to reproduce
1. Add a predicate with the CONTAINS operator.
```
        self.imposter.add_predicate(
            operator=Operator.CONTAINS,
            method='POST,
            path='/my_url',
            body={'int_value': 1},
        ).add_response(
            response_type=ResponseType.IS,
            body=json.dumps({'result': 'success'}),
        ).create()
```
2. Send a request to MB with curl
```
$ curl http://mountebank:3004/my_url --data '{"int_value": 1, "other": "values"}'
{"errors":[{"message":"actual.indexOf is not a function","name":"TypeError","stack":"TypeError: actual.indexOf is not a function\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:408:63\n    at testPredicate (/usr/local/lib/node_modules/mountebank/src/models/predicates.js:232:16)\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:299:20\n    at Array.every (<anonymous>)\n    at predicateSatisfied (/usr/local/lib/node_modules/mountebank/src/models/predicates.js:268:34)\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:296:20\n    at Array.every (<anonymous>)\n    at predicateSatisfied (/usr/local/lib/node_modules/mountebank/src/models/predicates.js:268:34)\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:296:20\n    at Array.every (<anonymous>)"}]}
```

#### Additional info
If I put 1 as string `"int_value": "1"` in curl request then MB works as expected
```
$ curl http://mountebank:3004/my_url --data '{"int_value": "1", "other": "values"}'
{"result":  "success"}
```

#### Software versions used

```
OS: Ubuntu
mountebank: 2.4.0
Installation method: docker image from the official hub.
```

#### Log
```
{"message":"[http:3004] ::ffff:172.19.0.6:50534 => POST /my_url","level":"info","timestamp":"2021-04-15T12:44:21.270Z"}
{"message":"[http:3004] ::ffff:172.19.0.6:50534 X=> {\"message\":\"actual.indexOf is not a function\",\"name\":\"TypeError\",\"stack\":\"TypeError: actual.indexOf is not a function\\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:408:63\\n    at testPredicate (/usr/local/lib/node_modules/mountebank/src/models/predicates.js:232:16)\\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:299:20\\n    at Array.every (<anonymous>)\\n    at predicateSatisfied (/usr/local/lib/node_modules/mountebank/src/models/predicates.js:268:34)\\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:296:20\\n    at Array.every (<anonymous>)\\n    at predicateSatisfied (/usr/local/lib/node_modules/mountebank/src/models/predicates.js:268:34)\\n    at /usr/local/lib/node_modules/mountebank/src/models/predicates.js:296:20\\n    at Array.every (<anonymous>)\"}","level":"error","timestamp":"2021-04-15T12:44:21.271Z"}
```

**Comment by s1r3m** [comment]
Yeah, I use a client. But I can reproduce it with curl only.
Here's a stub from UI:
```
{
  "predicates": [
    {
      "caseSensitive": false,
      "except": "",
      "xpath": null,
      "jsonpath": null,
      "contains": {
        "method": "POST",
        "path": "my_url",
        "body": {
          "int_value": 1
        }
      }
    }
  ],
  "responses": [
    {
      "is": {
        "statusCode": 200,
        "body": "{\"result\": \"success\"}",
        "_mode": "text"
      },
      "repeat": 1,
      "behaviors": []
    }
  ],
  "_links": {
    "self": {
      "href": "/imposters/3004/stubs/0"
    }
  }
}
```

**Comment by s1r3m** [comment]
And both requests are logged fine.
```
  "requests": [
    {
      "requestFrom": "::ffff:172.19.0.6:50912",
      "method": "POST",
      "path": "/my_url",
      "query": {},
      "headers": {
        "User-Agent": "curl/7.29.0",
        "Host": "mountebank:3004",
        "Accept": "*/*",
        "Content-Length": "16",
        "Content-Type": "application/x-www-form-urlencoded"
      },
      "body": "{\"int_value\": 1}",
      "ip": "::ffff:172.19.0.6",
      "form": {
        "{\"int_value\": 1}": null
      },
      "timestamp": "2021-04-15T14:27:56.675Z"
    },
    {
      "requestFrom": "::ffff:172.19.0.6:50914",
      "method": "POST",
      "path": "/my_url",
      "query": {},
      "headers": {
        "User-Agent": "curl/7.29.0",
        "Host": "mountebank:3004",
        "Accept": "*/*",
        "Content-Length": "18",
        "Content-Type": "application/x-www-form-urlencoded"
      },
      "body": "{\"int_value\": \"1\"}",
      "ip": "::ffff:172.19.0.6",
      "form": {
        "{\"int_value\": \"1\"}": null
      },
      "timestamp": "2021-04-15T14:28:00.199Z"
    }
  ]
```

**Comment by brunns** [comment]
The [Using JSON Predicates](http://www.mbtest.org/docs/api/json) page doesn't discuss using the `contains` operator, so I'm not sure what's going on here.

**Comment by s1r3m** [comment]
Using EQUALS predicate for partial matching works just fine.
