### ISSUE TITLE
2.5.0: /imposters returns internal server error

### ISSUE THREAD

**Issue by PascalSchumacher** [bbyars/mountebank#654]
After updating from mountebank `2.4.0` to `2.5.0` `/imposters` returns an internal server error when accessed with a web-browser as long as imposters exists. It works when there are no imposters.

#### Expected behaviour

`/imposters` displays a list of imposters when displayed with a web-browser.

#### Actual behaviour

`Internal Server Error` is displayed

#### Steps to reproduce

Create an imposter, e.g.

```
Request method: POST
Request URI: http://mountebank.xxx.xxx:80/imposters
Content-Type=text/plain; charset=ISO-8859-1
Body:
{"port": 4551,"protocol": "http","recordRequests": true}
```

#### Software versions used

```
OS         : linux
mountebank : 2.5.0
node.js    :
  (only if installed via npm)
Installation method :
  docker
```

#### Log contents in mb.log when running mb --loglevel debug

```
ReferenceError: /usr/local/lib/node_modules/mountebank/src/views/imposters.ejs:34
    32| 
    33|   <% imposters.forEach(imposter => { %>
 >> 34|   <%- include('_imposter') -%>
    35|   <% }); -%>
    36| </table>
    37| 

/usr/local/lib/node_modules/mountebank/src/views/_imposter.ejs:1
 >> 1| <tr id='imposter-<%= imposter.port %>'>
    2|   <td style='width: 15em;'><a href='<%= imposter._links.self.href %>'>
    3|     <%= imposter.name || imposter.protocol + ':' + imposter.port %>
    4|   </a></td>

imposter is not defined
    at eval (eval at compile (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:11:26)
    at _imposter (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:692:17)
    at include (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:690:39)
    at eval (eval at compile (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:29:17)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:26:18)
    at imposters (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/usr/local/lib/node_modules/mountebank/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/usr/local/lib/node_modules/mountebank/node_modules/express/lib/view.js:135:8)
```

By the way: Thank you very much for providing/developing mountebank! 👍

**Comment by dw-e8** [comment]
Hey @PascalSchumacher :)
The latest breaking EJS changes on 2.5.0 (using the new EJS 3.1.6) are the issue here, breaking the `imposters` page.
I found this by reading the "INCLUDES" documentation on the EJS home page - https://ejs.co/ 

If you need to just get going here's a fix:


I changed line 34 of src/views/imposters.ejs to read:
`<%- include('_imposter', {imposter:imposter}) -%>`
and that fixed it for me.

**Comment by bbyars** [comment]
Thanks for the fix!

**Comment by bbyars** [comment]
(FYI, it went out with the last release, I just forgot to close the issue)
