### ISSUE TITLE
Issue when adding stubs

### ISSUE THREAD

**Issue by ksjain95** [bbyars/mountebank#659]
#### Expected behaviour

... If there is a bad request when adding stubs to existing imposter it should return 400 .

#### Actual behaviour

... Mountebank crashes and closes 

#### Steps to reproduce
 add imposter. 
add stub to existing imposter with request like ->
{
    "index": 0,
  "stubs": {. // instead of "stub" give "stubs" . this crashes mountebank.
    "responses": [
      { "is": { "statusCode": 200,
      "body": "The time is right 1" }}
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/hdfc/4547/test3",
            "method": "POST"
          }
        },
        {
          "equals": { "body": { "title": "Harry Potter" } }
        }
      ]
    }]
  }
}
...

#### Software versions used

```
OS         : macOS
mountebank :
node.js    :
  (only if installed via npm)
Installation method :
  (npm, zip, tar, pkg, deb, rpm)
```

#### Log contents in mb.log when running mb --loglevel debug

```
Log contents here
```
**error thrown** ->         (stub.responses || []).forEach(response => {
              ^

TypeError: Cannot read properties of undefined (reading 'responses')
    at /Users/kshitijjain/.nvm/versions/node/v17.2.0/lib/node_modules/mountebank/src/models/compatibility.js:18:15
    at Array.forEach (<anonymous>)
    at upcastShellTransformToArray (/Users/kshitijjain/.nvm/versions/node/v17.2.0/lib/node_modules/mountebank/src/models/compatibility.js:17:27)
    at Object.upcast (/Users/kshitijjain/.nvm/versions/node/v17.2.0/lib/node_modules/mountebank/src/models/compatibility.js:107:5)
    at validateStubs (/Users/kshitijjain/.nvm/versions/node/v17.2.0/lib/node_modules/mountebank/src/controllers/imposterController.js:171:23)
    at async postStub (/Users/kshitijjain/.nvm/versions/node/v17.2.0/lib/node_modules/mountebank/src/controllers/imposterController.js:272:28)

**Comment by bbyars** [comment]
Thanks for reporting!
